export const LIST_DISPONIBILITIES_REQUEST = 'LIST_DISPONIBILITIES_REQUEST'
export const LIST_DISPONIBILITIES_SUCCESS = 'LIST_DISPONIBILITIES_SUCCESS'
export const LIST_DISPONIBILITIES_FAIL = 'LIST_DISPONIBILITIES_FAIL'

export const CREATE_DISPONIBILITY_REQUEST = 'CREATE_DISPONIBILITY_REQUEST'
export const CREATE_DISPONIBILITY_SUCCESS = 'CREATE_DISPONIBILITY_SUCCESS'
export const CREATE_DISPONIBILITY_FAIL = 'CREATE_DISPONIBILITY_FAIL'

export const EDIT_DISPONIBILITY_REQUEST = 'EDIT_DISPONIBILITY_REQUEST'
export const EDIT_DISPONIBILITY_SUCCESS = 'EDIT_DISPONIBILITY_SUCCESS'
export const EDIT_DISPONIBILITY_FAIL = 'EDIT_DISPONIBILITY_FAIL'

export const DELETE_DISPONIBILITY_REQUEST = 'DELETE_DISPONIBILITY_REQUEST'
export const DELETE_DISPONIBILITY_SUCCESS = 'DELETE_DISPONIBILITY_SUCCESS'
export const DELETE_DISPONIBILITY_FAIL = 'DELETE_DISPONIBILITY_FAIL'

export const RESERVE_DISPONIBILITY_REQUEST = 'RESERVE_DISPONIBILITY_REQUEST'
export const RESERVE_DISPONIBILITY_SUCCESS = 'RESERVE_DISPONIBILITY_SUCCESS'
export const RESERVE_DISPONIBILITY_FAIL = 'RESERVE_DISPONIBILITY_FAIL'

export const CONFIRM_DISPONIBILITY_REQUEST = 'CONFIRM_DISPONIBILITY_REQUEST'
export const CONFIRM_DISPONIBILITY_SUCCESS = 'CONFIRM_DISPONIBILITY_SUCCESS'
export const CONFIRM_DISPONIBILITY_FAIL = 'CONFIRM_DISPONIBILITY_FAIL'